const REGISTER_FAIL = 'REGISTER_FAIL';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const SUCCESS_MESSAGE_CLEAR = 'SUCCESS_MESSAGE_CLEAR';
const ERROR_CLEAR = 'ERROR_CLEAR';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';